# 전세계 행복도 지표 데이터

### 데이터 출처 :https://www.kaggle.com/unsdsn/world-happiness(참고, 데이터 수정)

### 데이터 설명 : 전세계 행복도 지표 조사

### data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv',encoding='utf-8')
df.head()

,행복랭킹,나라명,점수,상대GDP,사회적지원,행복기대치,선택의 자유도,관대함,부패에 대한인식,년도
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

### Question 1.
### 데이터는 2018년도와 2019년도의 전세계 행복 지수를 표현한다. 각년도의 행복랭킹 10위를 차지한 나라의 행복점수의 평균을 구하여라

In [5]:
result = df[df['행복랭킹'] ==10]['점수'].mean()
print(result)

7.259

### Question 2.
### 데이터는 2018년도와 2019년도의 전세계 행복 지수를 표현한다. 각년도의 행복랭킹 50위이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하라

In [6]:
result = df[df['행복랭킹']<=50][['년도','점수']].groupby('년도').mean()
print(result)

           점수
년도
2018  6.64678
2019  6.67002

### Question 3.
### 2018년도 데이터들만 추출하여 행복점수와 부패에 대한 인식에 대한 상관계수를 구하여라

In [9]:
result = df[df['년도'] ==2018][['점수','부패에 대한인식']].corr().iloc[0,1]
print(result)

0.40529152271510027

### Question 4.
### 2018년도와 2019년도의 행복랭킹이 변화하지 않은 나라명의 수를 구하여라

In [8]:
result = len(df[['행복랭킹','나라명']]) - len(df[['행복랭킹','나라명']].drop_duplicates())
print(result)

15

### Question 5.
### 2019년도 데이터들만 추출하여 각변수간 상관계수를 구하고 내림차순으로 정렬한 후 상위 5개를 데이터 프레임으로 출력하라. 컬럼명은 v1,v2,corr으로 표시하라

In [10]:
dataf = df[df['년도'] ==2019].corr().unstack().to_frame().reset_index().dropna()

result = dataf[dataf[0] !=1].sort_values(0,ascending=False).drop_duplicates(0)
answer = result.head(5).reset_index(drop=True)
answer.columns = ['v1','v2','corr']
display(answer)

      v1     v2      corr
0  행복기대치  상대GDP  0.835462
1  상대GDP     점수  0.793883
2  행복기대치     점수  0.779883
3  사회적지원     점수  0.777058
4  사회적지원  상대GDP  0.754906

### Question 6.
### 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하여라

In [11]:
result = df.groupby('년도').tail(5).groupby('년도').mean()[['점수']]
print(result)

          점수
년도
2018  3.1800
2019  3.1408

### Question 7.
### 2019년 데이터를 추출하고 해당데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을 각각 구하고 그 차이값을 출력하라

In [12]:
over = df[df['상대GDP'] >= df['상대GDP'].mean()]['점수'].mean()
under = df[df['상대GDP'] <= df['상대GDP'].mean()]['점수'].mean()

result = over - under
print(result)

1.4212148925537225

### Question 8.
### 각 년도의 부패에 대한인식을 내림차순 정렬했을때 상위 20개 국가의 부패에 대한인식의 평균을 구하여라

In [13]:
result = df.sort_values(['년도','부패에 대한인식'],ascending=False).groupby('년도').head(20).groupby(['년도']).mean()[['부패에 대한인식']]
print(result)

      부패에 대한인식
년도
2018    0.3267
2019    0.3201

### Question 9.
### 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하여라

In [15]:
result = set(df[(df['년도']==2018) & (df['행복랭킹'] <=50)]['나라명'])  -set(df[(df['년도']==2019) & (df['행복랭킹'] <=50)]['나라명'])
answer = len(result)
print(answer)

4

### Question 10.
### 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [16]:
count = df['나라명'].value_counts()
target = count[count>=2].index

df2 = df.copy()
multiple = df2[df2['나라명'].isin(target)].reset_index(drop=True)
multiple.loc[multiple['년도']==2018,'점수'] = multiple[multiple['년도'] ==2018]['점수'].values * (-1)
result = multiple.groupby('나라명').sum()['점수'].sort_values().to_frame().iloc[-1]
result

점수    0.87
Name: Burundi, dtype: float64