# 포켓몬 정보 데이터

### 데이터 출처 : https://www.kaggle.com/abcsds/pokemon (참고, 데이터 수정)

### 데이터 설명 : 포켓몬 정보

### data url = https://raw.githubusercontent.com/Datamanim/datarepo/main/pok/Pokemon.csv

In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/pok/Pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Question 1.
### Legendary 컬럼은 전설포켓몬 유무를 나타낸다.전설포켓몬과 그렇지 않은 포켓몬들의 HP평균의 차이를 구하여라

In [3]:
target = df.groupby('Legendary').mean()['HP']
result = target.values[1] -target.values[0]
print(result)

25.55614861329147

### Question 2.
### Type 1은 주속성 Type 2 는 부속성을 나타낸다. 가장 많은 부속성 종류는 무엇인가?

In [4]:
result = df['Type 2'].value_counts().index[0]
print(result)

Flying

### Question 3.
### 가장 많은 Type 1 의 종의 평균 Attack 을 평균 Defense로 나눈값은?

In [5]:
Max = df['Type 1'].value_counts().index[0]

result = df[df['Type 1']== Max].Attack.mean() /df[df['Type 1']== Max].Defense.mean()
print(result)

1.0165238678090576

### Question 4.
### 포켓몬 세대(Generation) 중 가장 많은 Legendary를 보유한 세대는 몇 세대인가?

In [7]:
result = df[df.Legendary==True].Generation.value_counts().index[0]
result

3

### Question 5.
### ‘HP’, ‘Attack’, ‘Defense’, ‘Sp. Atk’, ‘Sp. Def’, ‘Speed’ 간의 상관 계수중 가장 절댓값이 큰 두 변수와 그 값을 구하여라

In [8]:
target = df[[ 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']].corr().unstack().reset_index().rename(columns={0: "corr"})
result = target[target['corr']!=1].sort_values('corr',ascending=False).iloc[0]
print(result)

level_0     Sp. Def
level_1     Defense
corr       0.510747
Name: 26, dtype: object

### Question 6.
### 각 Generation의 Attack으로 오름차순 정렬시 상위 3개 데이터들(18개)의 Attack의 전체 평균을 구하여라

In [9]:
result = df.sort_values(['Generation','Attack']).groupby('Generation').head(3).Attack.mean()
print(result)

19.5

### Question 7.
### 각 Generation의 Attack으로 내림차순 정렬시 상위 5개 데이터들(30개)의 Attack의 전체 평균을 구하여라

In [13]:
result =  df.sort_values(['Generation','Attack'],ascending=False).groupby('Generation').head(5).Attack.mean()
print(result)

157.23333333333332

### Question 8.
### 가장 흔하게 발견되는 (Type1 , Type2) 의 쌍은 무엇인가?

In [12]:
result = df[['Type 1','Type 2']].value_counts().head(1)
print(result)

Type 1  Type 2
Normal  Flying    24
dtype: int64

### Question 9.
### 한 번씩만 존재하는 (Type1 , Type2)의 쌍의 갯수는 몇 개인가?

In [11]:
target = df[['Type 1','Type 2']].value_counts()
result = len(target[target==1])
print(result)

39

### Question 10.
### 한번씩만 존재하는 (Type1 , Type2)의 쌍을 각 세대(Generation)은 각각 몇개씩 가지고 있는가?

In [15]:
target = df[['Type 1','Type 2']].value_counts()
target2 = target[target==1]

lst = []
for value in target2.reset_index().values:
    t1 = value[0]
    t2 = value[1]
    
    sp = df[(df['Type 1']==t1) & (df['Type 2']==t2)]
    lst.append(sp)

result = pd.concat(lst).reset_index(drop=True).Generation.value_counts().sort_index()
print(result)

1     1
2     4
3     5
4    13
5     7
6     9
Name: Generation, dtype: int64