# 의료 비용 예측 데이터

### 데이터 출처 :https://www.kaggle.com/mirichoi0218/insurance/code(참고, 데이터 수정)

### 데이터 설명 : 의료비용 예측문제

### Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/train.csv

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/train.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   64  female  39.330         0     no  northeast  14901.51670
1   47  female  27.830         0    yes  southeast  23065.42070
2   52  female  33.300         2     no  southwest  10806.83900
3   33  female  22.135         1     no  northeast   5354.07465
4   30    male  31.400         1     no  southwest   3659.34600

### Question 1.
### 흡연자와 비흡연자 각각 charges의 상위 10% 그룹의 평균의 차이는?

In [3]:
high = df.loc[df.smoker =='yes'].charges.quantile(0.9)
high2 = df.loc[df.smoker =='no'].charges.quantile(0.9)
mean_yes = df.loc[(df.smoker =='yes') &(df.charges >=high)].charges.mean()
mean_no = df.loc[(df.smoker =='no') &(df.charges >=high2)].charges.mean()
answer = mean_yes - mean_no
print(answer)

29297.954548156158